import {environment} from '../../environments/environment';

export const API_URL = environment.apiUrl + '/api';
export const CHARITY = '/projects';
export const IMAGE = '/image';
export const CATEGORY = '/categories';
export const ACCOUNT = '/accounts';
export const ACCOUNT_WITH_TYPE = '/accounts/accountTypes';
export const PAUSE = '/pause';
export const ACTIVATE = '/activate';
export const TERNINATE = '/end';
export const REDIRECT = '/redirect';
export const CALLBACK = '/callback';
export const USERS = '/users';
export const USERS_PROFILE = '/users/profile';
export const USERS_PROFILE2 = '/profiles';
export const IMG_URL = environment.apiUrl + '/img/';
export const CURRENT_ORGANIZATION = '1';
export const INFURA_URL = 'https://ropsten.infura.io/v3/' + environment.infuraApiKey;
// export const IMG_URL = 'http://127.0.0.1:8887/';
export const BADGE = '/badges';
export const DONATE = '/donate';
export const DEFAULT_ACCOUNT = '/default';
export const TRANSACTIONS = '/transactions';
export const PROJECT = '/project';
